/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
  // RCC AHB1ENR base address
  uint32_t *pClkCtrlRegGPIOC = (uint32_t*) 0x40023830;  // RCC AHB1 peripheral clock enable register
  uint32_t *pClkCtrlRegGPIOA = (uint32_t*) 0x40023830;  // Same register for GPIOA

  // GPIOC (LED on PC13)
  uint32_t *pPortC13ModeReg = (uint32_t*) 0x40020800;   // GPIOC MODER
  uint32_t *pPortC13OutReg  = (uint32_t*) 0x40020814;   // GPIOC ODR

  // GPIOA (Button/input on PA0)
  uint32_t *pPortA0ModeReg  = (uint32_t*) 0x40020000;   // GPIOA MODER
  uint32_t *pPortA0InputReg = (uint32_t*) 0x40020010;   // GPIOA IDR

  // 1. Enable clocks for GPIOC and GPIOA
  *pClkCtrlRegGPIOC |= (1 << 2);  // Bit 2 enables GPIOC
  *pClkCtrlRegGPIOA |= (1 << 0);  // Bit 0 enables GPIOA

  // 2. Configure PC13 as output (MODER13 = 01)
  *pPortC13ModeReg &= ~(0x3 << 26);  // Clear MODER13 bits [27:26]
  *pPortC13ModeReg |=  (0x1 << 26);  // Set MODER13 = 01 (output)

  // 3. Configure PA0 as input (MODER0 = 00)
  *pPortA0ModeReg &= ~(0x3 << 0);    // Clear MODER0 bits [1:0] (input mode)

  while (1)
  {
    // 5. Read PA0 input
    uint32_t pinStatus = (*pPortA0InputReg & 0x1); // Read PA0 state

    // 6. Control PC13 LED (active-low)
    if (pinStatus) {
        *pPortC13OutReg &= ~(1 << 13);  // Set PC13 LOW → LED ON
    } else {
        *pPortC13OutReg |=  (1 << 13);  // Set PC13 HIGH → LED OFF
    }
  }
}
